In [3]:
import numpy as np

In [4]:
l = [1, 2, 3, 4, 5,6]


In [5]:
arr = np.array(l)

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
print(arr)

[1 2 3 4 5 6]


In [8]:
l = [[1, 2, 3],[4, 5, 6]]

In [12]:
arr2d = np.array(l)

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2d.shape

(2, 3)

In [20]:
l = [[[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]]]

In [21]:
arr3d = np.array(l)

In [22]:
arr3d

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]])

In [23]:
arr3d.shape

(1, 3, 6)

In [24]:
l = [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18]]

In [25]:
arr = np.array(l)

In [26]:
arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18]])

In [32]:
arr.shape

(18, 1)

In [33]:
l = [[[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18]]]

In [34]:
arr = np.array(l)

In [35]:
arr

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18]]])

In [36]:
arr.shape

(1, 18, 1)

In [37]:
l = [[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]]

In [38]:
arr = np.array(l)

In [39]:
arr.shape

(1, 1, 18)

In [40]:
arr = np.reshape(arr,(18,1,1))

In [41]:
arr.shape

(18, 1, 1)

In [42]:
a = arr[3:8, :, :]

In [43]:
a

array([[[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])

In [44]:
l = [1,2,3,4,5,6,7,8]

In [45]:
arr = np.array(l)

In [46]:
l2 = l*2

In [47]:
l2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [48]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
arr2 = arr*2

In [50]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [51]:
arr3 = arr*2.5

In [52]:
arr3

array([ 2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [53]:
l4 = l2 + l

In [54]:
l4

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [55]:
arr4 = arr2 + arr3

In [56]:
arr4

array([ 4.5,  9. , 13.5, 18. , 22.5, 27. , 31.5, 36. ])

In [57]:
arr5 = arr4 + 2

In [58]:
arr5

array([ 6.5, 11. , 15.5, 20. , 24.5, 29. , 33.5, 38. ])

In [59]:
arr6 = arr4 + 5.9

In [60]:
arr6

array([10.4, 14.9, 19.4, 23.9, 28.4, 32.9, 37.4, 41.9])

In [61]:
arr4.shape

(8,)

In [62]:
arr5.shape

(8,)

In [63]:
arr5 = arr5.reshape(1,8)

In [64]:
arr5.shape

(1, 8)

In [65]:
arr5

array([[ 6.5, 11. , 15.5, 20. , 24.5, 29. , 33.5, 38. ]])

In [66]:
arr6 = arr4 + arr5

In [67]:
arr6

array([[11., 20., 29., 38., 47., 56., 65., 74.]])

In [68]:
arr5 = arr5.reshape(8,1)

In [69]:
arr5.shape

(8, 1)

In [70]:
arr6 = arr4 + arr5

In [71]:
arr6

array([[11. , 15.5, 20. , 24.5, 29. , 33.5, 38. , 42.5],
       [15.5, 20. , 24.5, 29. , 33.5, 38. , 42.5, 47. ],
       [20. , 24.5, 29. , 33.5, 38. , 42.5, 47. , 51.5],
       [24.5, 29. , 33.5, 38. , 42.5, 47. , 51.5, 56. ],
       [29. , 33.5, 38. , 42.5, 47. , 51.5, 56. , 60.5],
       [33.5, 38. , 42.5, 47. , 51.5, 56. , 60.5, 65. ],
       [38. , 42.5, 47. , 51.5, 56. , 60.5, 65. , 69.5],
       [42.5, 47. , 51.5, 56. , 60.5, 65. , 69.5, 74. ]])

In [72]:
arr6.shape

(8, 8)

In [73]:
arr4 = np.array([1,2,3,4,5,5,67,78,8,8,9,9])

In [74]:
arr4.shape

(12,)

In [75]:
arr5 = np.array([1,2,3,4,5,6,7,7,8,8,9,9,0,9])

In [76]:
arr5.shape

(14,)

In [77]:
arr5 = arr5.reshape(14,1)

In [78]:
arr6 = arr4 + arr5

In [79]:
arr6.shape

(14, 12)

In [80]:
arr5 = arr5.reshape(7,2)

In [81]:
arr6 = arr4 + arr5

ValueError: operands could not be broadcast together with shapes (12,) (7,2) 

In [82]:
arr5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [83]:
arr5 = arr5.reshape(2,12)

In [84]:
arr5.shape

(2, 12)

In [85]:
arr6 = arr4 + arr5

In [86]:
arr6.shape

(2, 12)

In [87]:
arr6

array([[ 2,  4,  6,  8, 10, 11, 74, 86, 17, 18, 20, 21],
       [14, 16, 18, 20, 22, 23, 86, 98, 29, 30, 32, 33]])

In [88]:
arr4

array([ 1,  2,  3,  4,  5,  5, 67, 78,  8,  8,  9,  9])