In [3]:
import numpy as np

In [4]:
l = [1, 2, 3, 4, 5,6]


In [5]:
arr = np.array(l)

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
print(arr)

[1 2 3 4 5 6]


In [8]:
l = [[1, 2, 3],[4, 5, 6]]

In [12]:
arr2d = np.array(l)

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2d.shape

(2, 3)

In [20]:
l = [[[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]]]

In [21]:
arr3d = np.array(l)

In [22]:
arr3d

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]])