In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4, 5,6]


In [4]:
arr = np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
print(arr)

[1 2 3 4 5 6]


In [7]:
l = [[1, 2, 3],[4, 5, 6]]

In [8]:
arr2d = np.array(l)

In [9]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2d.shape

(2, 3)

In [11]:
l = [[[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]]]

In [12]:
arr3d = np.array(l)

In [13]:
arr3d

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]])

In [14]:
arr3d.shape

(1, 3, 6)

In [15]:
l = [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18]]

In [16]:
arr = np.array(l)

In [17]:
arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18]])

In [18]:
arr.shape

(18, 1)

In [19]:
l = [[[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18]]]

In [20]:
arr = np.array(l)

In [21]:
arr

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18]]])

In [22]:
arr.shape

(1, 18, 1)

In [23]:
l = [[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]]

In [24]:
arr = np.array(l)

In [25]:
arr.shape

(1, 1, 18)

In [26]:
arr = np.reshape(arr,(18,1,1))

In [27]:
arr.shape

(18, 1, 1)

In [28]:
a = arr[3:8, :, :]

In [29]:
a

array([[[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])

In [30]:
l = [1,2,3,4,5,6,7,8]

In [31]:
arr = np.array(l)

In [32]:
l2 = l*2

In [33]:
l2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [34]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr2 = arr*2

In [36]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [37]:
arr3 = arr*2.5

In [38]:
arr3

array([ 2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [39]:
l4 = l2 + l

In [40]:
l4

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [41]:
arr4 = arr2 + arr3

In [42]:
arr4

array([ 4.5,  9. , 13.5, 18. , 22.5, 27. , 31.5, 36. ])

In [43]:
arr5 = arr4 + 2

In [44]:
arr5

array([ 6.5, 11. , 15.5, 20. , 24.5, 29. , 33.5, 38. ])

In [45]:
arr6 = arr4 + 5.9

In [46]:
arr6

array([10.4, 14.9, 19.4, 23.9, 28.4, 32.9, 37.4, 41.9])

In [47]:
arr4.shape

(8,)

In [48]:
arr5.shape

(8,)

In [49]:
arr5 = arr5.reshape(1,8)

In [50]:
arr5.shape

(1, 8)

In [51]:
arr5

array([[ 6.5, 11. , 15.5, 20. , 24.5, 29. , 33.5, 38. ]])

In [52]:
arr6 = arr4 + arr5

In [53]:
arr6

array([[11., 20., 29., 38., 47., 56., 65., 74.]])

In [54]:
arr5 = arr5.reshape(8,1)

In [55]:
arr5.shape

(8, 1)

In [56]:
arr6 = arr4 + arr5

In [57]:
arr6

array([[11. , 15.5, 20. , 24.5, 29. , 33.5, 38. , 42.5],
       [15.5, 20. , 24.5, 29. , 33.5, 38. , 42.5, 47. ],
       [20. , 24.5, 29. , 33.5, 38. , 42.5, 47. , 51.5],
       [24.5, 29. , 33.5, 38. , 42.5, 47. , 51.5, 56. ],
       [29. , 33.5, 38. , 42.5, 47. , 51.5, 56. , 60.5],
       [33.5, 38. , 42.5, 47. , 51.5, 56. , 60.5, 65. ],
       [38. , 42.5, 47. , 51.5, 56. , 60.5, 65. , 69.5],
       [42.5, 47. , 51.5, 56. , 60.5, 65. , 69.5, 74. ]])

In [58]:
arr6.shape

(8, 8)

In [59]:
arr4 = np.array([1,2,3,4,5,5,67,78,8,8,9,9])

In [60]:
arr4.shape

(12,)

In [61]:
arr5 = np.array([1,2,3,4,5,6,7,7,8,8,9,9,0,9])

In [62]:
arr5.shape

(14,)

In [63]:
arr5 = arr5.reshape(14,1)

In [64]:
arr6 = arr4 + arr5

In [65]:
arr6.shape

(14, 12)

In [66]:
arr5 = arr5.reshape(7,2)

In [67]:
arr6 = arr4 + arr5

ValueError: operands could not be broadcast together with shapes (12,) (7,2) 

In [68]:
arr5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [69]:
arr5 = arr5.reshape(2,12)

In [70]:
arr5.shape

(2, 12)

In [71]:
arr6 = arr4 + arr5

In [72]:
arr6.shape

(2, 12)

In [73]:
arr6

array([[ 2,  4,  6,  8, 10, 11, 74, 86, 17, 18, 20, 21],
       [14, 16, 18, 20, 22, 23, 86, 98, 29, 30, 32, 33]])

In [74]:
arr4

array([ 1,  2,  3,  4,  5,  5, 67, 78,  8,  8,  9,  9])

In [75]:
arr4 = arr4.reshape(1,12)

In [76]:
arr4.shape

(1, 12)

In [77]:
arr5.shape

(2, 12)

In [78]:
arr = np.zeros((2,5))

In [79]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
arr = np.ones((2,5))

In [83]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
arr = np.empty((2,5),dtype = int)

In [89]:
arr

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408]])

In [90]:
arr = np.linspace(0,10,20)

In [91]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [93]:
arr = np.arange(0,10,2)

In [94]:
arr

array([0, 2, 4, 6, 8])

In [95]:
arr = np.random.binomial(n=6, p=0.5, size=(2, 5))

In [96]:
arr

array([[2, 4, 3, 1, 3],
       [4, 4, 3, 2, 3]])

In [97]:
arr = np.random.binomial(n=1, p= 0.5, size =(2, 5))

In [98]:
arr

array([[0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [99]:
sample_arr =np.arange(0,60,5)

In [100]:
sample_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [103]:
arr = np.random.choice(sample_arr, size = (2,50), replace = True)

In [104]:
arr

array([[10,  5,  0, 40, 10, 15, 45,  5,  5, 35, 50, 15, 55, 25, 15, 25,
        20,  0, 10, 55, 15, 15, 30, 25, 20, 45, 15, 45, 30, 45, 25, 35,
         0, 25, 35, 30, 20, 25,  0, 50, 30, 15, 45, 10, 40, 45, 20,  5,
        40, 20],
       [25, 55, 35, 15, 10, 35, 10, 55, 25, 50, 45, 10, 15, 20,  0, 35,
        40, 20, 40, 25, 55, 30, 25, 50, 10, 30, 30, 55,  0, 45, 40, 35,
         5, 25, 15, 20, 15, 15, 40, 55, 55, 30, 15, 25, 15, 15, 35, 45,
        55,  0]])

In [107]:
arr = np.random.multivariate_normal(mean = [1,2,3], cov = [[1,0,0],[0,2,0],[0,0,3]], size = 10)

In [108]:
arr

array([[-0.66450145,  0.61509301,  5.05510114],
       [-0.0189648 ,  0.38626356,  5.2174271 ],
       [ 2.98462818,  2.11597447,  5.34021783],
       [ 1.21071657,  4.02199711,  5.91124345],
       [ 1.78000718,  1.42855195,  1.01557787],
       [ 0.95400716,  1.4858652 ,  5.17031605],
       [ 0.74611924,  2.12863221,  2.76337216],
       [ 2.54190059,  1.15736294,  2.83137008],
       [ 0.19252096,  4.36683266,  2.08051123],
       [ 1.80627568,  0.12784408,  6.05795237]])

In [109]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [110]:
arr

array([[4.61347614, 5.64113631, 6.05374321, 3.3767518 , 4.55988415,
        4.07720559, 5.61436364, 2.32722629, 4.90408478, 4.88050021],
       [4.48115599, 4.74329443, 3.76336463, 6.60621861, 4.87763211,
        3.54591287, 5.28330663, 5.26210385, 6.92229571, 6.18136553]])

In [111]:
arr = np.random.rand(2,10)

In [112]:
arr

array([[0.21042036, 0.74135248, 0.62777385, 0.35565063, 0.40616381,
        0.65079944, 0.39776947, 0.92842047, 0.2449156 , 0.94584634],
       [0.73722031, 0.7951188 , 0.85278593, 0.16524057, 0.95732522,
        0.68787416, 0.35305232, 0.20622466, 0.05425314, 0.28971661]])

In [113]:
arr = np.random.randint(low=10, high=25, size=(2,10))

In [114]:
arr

array([[24, 12, 17, 15, 23, 15, 18, 12, 20, 16],
       [18, 14, 16, 19, 22, 21, 21, 13, 12, 10]])

In [117]:
arr = np.random.randn(2, 10)

In [118]:
arr

array([[ 0.46943211, -1.94494522, -0.65166793, -0.15197706,  0.11079053,
        -2.13573672,  0.75575071,  0.44845125,  0.46341795,  0.52545833],
       [-0.3098778 , -0.22459806,  0.06209947,  0.0729087 ,  0.26071133,
         0.02450245,  0.92447343,  1.88306887, -0.0900629 , -0.81263408]])

In [119]:
arr = np.eye(3)

In [120]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
arr = np.eye(3,4)

In [122]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [123]:
arr = np.eye(4,3)

In [124]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [125]:
arr = np.logspace(start = -2, stop = 3, base = 10, num = 5)

In [126]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [129]:
arr = np.logspace(start = -2, stop = 3, base = 2, num = 6)

In [130]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

In [133]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.5,size=(2,6))

In [134]:
rowwise_concat_arr = np.concatenate((left_arr, right_arr), axis=0)
colwise_concat_arr = np.concatenate((left_arr, right_arr), axis=1)

In [135]:
rowwise_concat_arr

array([[1, 3, 3, 2, 3, 3],
       [3, 2, 1, 2, 2, 4],
       [8, 5, 7, 5, 6, 5],
       [4, 7, 4, 4, 7, 6]])

In [136]:
colwise_concat_arr

array([[1, 3, 3, 2, 3, 3, 8, 5, 7, 5, 6, 5],
       [3, 2, 1, 2, 2, 4, 4, 7, 4, 4, 7, 6]])

In [139]:
bmask = np.ones((colwise_concat_arr.shape[1],),dtype=bool)

In [140]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [141]:
bmask[1] = False
bmask[5] = False

In [142]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True])

In [143]:
colwise_concat_arr[:, bmask]

array([[1, 3, 2, 3, 8, 5, 7, 5, 6, 5],
       [3, 1, 2, 2, 4, 7, 4, 4, 7, 6]])

In [144]:
bmask = np.ones((rowwise_concat_arr.shape[0],),dtype=bool)

In [145]:
bmask

array([ True,  True,  True,  True])

In [146]:
bmask[1] = False
bmask[2] = False

In [147]:
bmask

array([ True, False, False,  True])

In [148]:
rowwise_concat_arr[bmask, :]

array([[1, 3, 3, 2, 3, 3],
       [4, 7, 4, 4, 7, 6]])

In [150]:
arr = np.random.randint(low=0,high=20,size=(1,2,3,4,5))

In [151]:
arr

array([[[[[ 5,  3, 17, 18, 14],
          [ 2, 14,  1,  3,  9],
          [17, 14,  0, 16, 10],
          [19, 12, 11,  8, 17]],

         [[16, 10,  3,  1,  8],
          [11,  4,  1,  5, 19],
          [ 5,  3,  3, 10,  5],
          [ 4, 13, 12, 13,  7]],

         [[ 6,  9,  6, 16,  3],
          [ 7, 12,  5,  0,  9],
          [ 6, 19,  0, 19,  2],
          [ 9, 19,  9,  3, 15]]],


        [[[ 7, 17, 10, 14, 11],
          [ 7, 18, 19,  9,  5],
          [ 2, 12, 17,  2,  1],
          [15,  2,  4,  7,  6]],

         [[ 8,  1, 16, 11,  3],
          [ 5, 17,  1, 19, 13],
          [15,  4,  9,  5,  4],
          [ 8,  1, 13,  9,  2]],

         [[15,  3,  4, 15,  2],
          [14,  6,  5, 18,  8],
          [ 1,  9,  7, 14, 12],
          [ 3, 17,  6, 10, 19]]]]])

In [152]:
arr = arr[:,:,np.newaxis,...]

In [153]:
arr.shape

(1, 2, 1, 3, 4, 5)

In [154]:
squeezed_arr = np.squeeze(arr)

In [156]:
squeezed_arr.shape

(2, 3, 4, 5)